openapi: "3.0.0"
CustomerId:
  required:
    - id
    - integrationCode
    - authenticatedState
  type: object
  properties:
    id:
      type: string
      maxLength: 128
    integrationCode:
      type: string
      maxLength: 50
      description: This is the **alias** used when setting up a CRS datasource in the Marketing Cloud UI.
    authenticatedState:
      $ref: "./AuthenticatedState.yaml#/AuthenticatedState"
