openapi: "3.0.0"
QAModePreviewIndex:
  type: object
  properties:
    activityIndex:
      type: integer
      minimum: 1
      description: |
        Index references the activity in the activity list (from the encrypted token).
        Validation
          * If the activity list index is out of boundaries of the activities list in the token or if it is null it will  be ignored.
          * Activity list index starts with 1.
          * Should be at least one activity index, and should reference an activity specified in the token.
    experienceIndex:
      type: integer
      minimum: 1
      description: |
        When specified, the experience with this index in the activity definition will be selected.
        Validation
          * Can be null (unspecified)
          * If index is not specified or out of bounds, the experience will be selected via activity experience selector strategy.
          * Experience index starts with 1.
