openapi: "3.0.0"
DeliveryResponse:
  type: object
  description: Delivery response. Returned content will be based upon the request and client's active activities.
  properties:
    status:
      type: integer
    requestId:
      type: string
      description: |
        ID of the processed request.
        If it's not sent in the request, a random ID (UUID) is generated and returned with the response.
    id:
      $ref: "../../common/components/VisitorId.yaml#/VisitorId"
    client:
      type: string
      description: Client's code. The one which was sent in the request's path.
    edgeHost:
      description: Cluster host name that served the response. Ideally, all subsequent requests should be made to that host.
      type: string
    execute:
      $ref: "./ExecuteResponse.yaml#/ExecuteResponse"
    prefetch:
      $ref: "./PrefetchResponse.yaml#/PrefetchResponse"
    notifications:
      type: array
      $ref: "./NotificationResponse.yaml#/NotificationResponse"
    
