openapi: "3.0.0"
NotificationView:
  type: object
  description: Notification for the displayed view.
  properties:
    name:
      type: string
      maxLength: 128
      description: |
        View Name - Unique view name. If the activity has a metric with a view with this name it will be matched,
        providing the Key matches as well or is null and view and metric targeting is matched.
    key:
      type: string
      maxLength: 512
      description: |
        View Key - An optional encoded String identifier used in advanced scenarios, such as View fingerprinting.
        Same matching conditions as for View Name.
    state:
      type: string
      description: View state token.
