openapi: "3.0.0"
PrefetchResponse:
  type: object
  description: |
    The object that will return the prefetched content based on the request, active activities etc
  properties:
    views:
      type: array
      description: |
        Contains all the views matching the request.
      items:
        $ref: "./View.yaml#/View"
    pageLoad:
      $ref: "./PageLoadResponse.yaml#/PageLoadResponse"
    mboxes:
      type: array
      description: |
        Prefetched mboxes, including content and notification tokens to be sent back when the mboxes are displayed.
      items:
        $ref: "./PrefetchMboxResponse.yaml#/PrefetchMboxResponse"
    metrics:
      type: array
      description: |
        Click track metrics that are not assigned with a view but are present in activities that have views.
        If the same activity is serving content for selectors on a view and selectors unassociated with
        views, and having click track metrics not associated with any view within the activity, then:
          * in case of a prefetch-only request, these metrics (tokens) will be set in the prefetch response's metrics.
          * in case of an execute-only request, the metrics will be set in the pageLoad response's metrics.
          * in case of a request, with both execute and prefetch, the metrics will be set in the pageLoad response's metrics only.
      items:
        $ref: "./Metric.yaml#/Metric"
